#! /bin/bash

on:
  pull_request:
    types: [opened]

jobs:
  shortcut-create:
    runs-on: ubuntu-latest
    steps:
      - uses: Grayscale-Labs/create-linked-shortcut-story@sanfordleach/sc-4894/fix-clubhouse-story-gh-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          shortcut-token: ${{ secrets.SHORTCUT_TOKEN }}
          project-name: app.gograyscale.com
